services:
  db:
    image: mysql:8.0
    container_name: mysql_modeling_04
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3310"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
